# -*- coding: utf-8 -*-
"""
Created on Tue May 19 17:33:09 2020

@author: robert.culver
"""

import numpy as np
from numba import jit
from _utilities.tools import portionOutList

def getPhotonMap(detShape, pixSize, sdd, N_avg_max = 1):
    '''
    Generates clean photon map image
    
    args:
        detShape    tuple of (N,M) for N by M pixels
        pixSize     size of each pixel in units of choice
        sdd         size of each pixel in units of choice
        N_avg_max   average number of photons at highest flux pixel (measured at pixel)
    '''
    xs, ys = np.meshgrid(*[pixSize*(np.arange(i) - i/2 + 0.5) for i in detShape])
    r_detPlane = np.sqrt(xs*xs + ys*ys) # radial distance from centre of det, in det plane
    r = np.sqrt(sdd*sdd + r_detPlane*r_detPlane)
    bright = (N_avg_max*sdd*sdd/(r*r))
    return bright
    
@jit
def getNoisy(bright, N_proj):
    '''
    Generates a noisy version of a clean bright photon map image
    output shape is clean.shape + (N_proj,)
    
    args:
        clean       clean photon map, as generated by getClean
        N_proj      number of noisy images to make
    '''
    detShape = bright.shape
    noisy = np.zeros(detShape + (N_proj,))
    for iy in range(int((detShape[0] + 1)/2)):
        for ix in range(int((detShape[1] + 1)/2)):
            rands = np.random.poisson(bright[iy,ix], size = N_proj*4).reshape(4,-1)
            noisy[ iy,  ix] = rands[0]
            noisy[-iy-1,  ix] = rands[1]
            noisy[ iy, -ix-1] = rands[2]
            noisy[-iy-1, -ix-1] = rands[3]
    return noisy.transpose(2,0,1)

@jit
def getNoisy2(img):
    '''
    Generates a noisy version of a clean bright photon map image
    output shape is clean.shape + (N_proj,)
    
    args:
        clean       clean photon map, as generated by getClean
        N_proj      number of noisy images to make
    '''
#    portions = portionOutList(img, 128)
#    output = np.zeros_like(img)
#    lengths = [len(p) for p in portions]
#    s = np.cumsum([0] + lengths[:-1])
#    e = np.cumsum(lengths)
#    for i in range(len(portions)):
#        output[s[i]:e[i]] = np.random.poisson(portions[i])
#    return output

    output = np.zeros_like(img)
    for i in range(output.shape[0]):
        output[i] = np.random.poisson(img[i])
    return output
    
    

def _test(show = True):
    import matplotlib.pyplot as plt
    # define para
    sdd = 500 # source-detector distance
    N_avg_max = 200 # average number of photons collected at detector central pixel
    N_proj = 1 # N projections
    detShape = (100,100)
    pixSize = 0.4 # mm
    # run calcs
    clean = getPhotonMap(detShape, pixSize, sdd, N_avg_max)
    noisy = getNoisy(clean, N_proj)
    # plot
    f, ax = plt.subplots(1,3, figsize = (10,10))
    img = noisy[0]/clean - 1
    ax[0].imshow(clean/N_avg_max, vmin = 0.0, vmax = 1)
    ax[1].imshow(noisy[0]/N_avg_max, vmin = 0.0, vmax = 1)
    ax[2].imshow(img, vmin = -1*img.std(), vmax = 1*img.std(), cmap = 'bwr')#, vmax = N_avg_max, vmin = 0, interpolation='nearest')    
    plt.show()
    f, ax = plt.subplots(1,3, figsize = (10,10))
    img2 = (noisy[0].astype(np.float16)/clean.astype(np.float16) - 1).astype(np.float64)
    print(clean.astype(np.float16).min())
    ax[0].imshow(clean/N_avg_max, vmin = 0.0, vmax = 1)
    ax[1].imshow(noisy[0]/N_avg_max, vmin = 0.0, vmax = 1)
    ax[2].imshow(img2, vmin = -1*img.std(), vmax = 1*img.std(), cmap = 'bwr')#, vmax = N_avg_max, vmin = 0, interpolation='nearest')    
    plt.show()
    f, ax = plt.subplots(figsize = (10,10))
    ax.imshow(img-img2, vmin = -1*img.std(), vmax = 1*img.std(), cmap = 'bwr')
    plt.show()
    return clean, noisy